# Generated by Django 2.0.3 on 2018-05-30 07:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomandaBando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data_chiusura', models.DateTimeField(help_text='quando la domanda è stata conclusa')),
                ('data_protocollazione', models.DateTimeField(help_text='quando la domanda è stata protocolla/consegnata')),
                ('progressione_accettata', models.BooleanField(default=False, help_text='Marca questa domanda come idonea alla progressione. Se vero fa fede la data di protocollazione come Data ultima progressione')),
                ('descrizione', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text="Per eventuale disabilitazione d'ufficio come ad esempio una esclusione coatta dovuta a contenziosi o motivazioni di natura giuridica. Se una domanda è presente ma disabilitata il dipendente non potrà crearne una nuova")),
            ],
            options={
                'verbose_name': 'Domanda di partecipazione del Dipendente',
                'verbose_name_plural': 'Domande di partecipazione dei Dipendenti',
            },
        ),
        migrations.CreateModel(
            name='ModuloDomandaBando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('modulo_compilato', models.TextField()),
            ],
            options={
                'verbose_name': 'Modulo compilato Bando del Dipendente',
                'verbose_name_plural': 'Moduli compilati Bando dei Dipendenti',
            },
        ),
    ]
