# Generated by Django 2.0.3 on 2018-05-30 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0002_auto_20180530_0937'),
        ('gestione_risorse_umane', '0004_remove_dipendente_data_cessazione_contratto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domande_peo', '0002_auto_20180530_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilitazioneBandoDipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_peo.Bando')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-domande_peo_abilitazionebandodipendente_related+', related_query_name='created-domande_peo_abilitazionebandodipendentes+', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.Dipendente')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-domande_peo_abilitazionebandodipendente_related+', related_query_name='modified-domande_peo_abilitazionebandodipendentes+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Abilitazioni Dipendenti a partecipare al Bando',
                'verbose_name': 'Abilitazione Bando Dipendente',
            },
        ),
    ]
