# Generated by Django 2.0.3 on 2018-05-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0003_abilitazionebandodipendente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilitazionebandodipendente',
            options={'verbose_name': 'Abilitazione al Bando per Dipendente', 'verbose_name_plural': 'Abilitazioni di partecipazione ai Bandi per i Dipendenti'},
        ),
    ]
