# Generated by Django 2.0.3 on 2018-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0005_auto_20180530_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulodomandabando',
            name='aiuto',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
