# Generated by Django 2.0.3 on 2018-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0008_remove_modulodomandabando_dipendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domandabando',
            name='data_chiusura',
            field=models.DateTimeField(blank=True, help_text='quando la domanda è stata conclusa', null=True),
        ),
        migrations.AlterField(
            model_name='domandabando',
            name='data_protocollazione',
            field=models.DateTimeField(blank=True, help_text='quando la domanda è stata protocolla/consegnata', null=True),
        ),
    ]
