# Generated by Django 2.0.3 on 2018-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0010_auto_20180604_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='punteggio_calcolato',
            field=models.FloatField(blank=True, help_text='popolato da Azione', null=True),
        ),
    ]
