# Generated by Django 2.0.3 on 2018-06-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0011_domandabando_punteggio_calcolato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domandabando',
            name='dipendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestione_risorse_umane.Dipendente'),
        ),
    ]
