# Generated by Django 2.0.3 on 2018-06-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0012_auto_20180606_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulodomandabando',
            options={'ordering': ['descrizione_indicatore'], 'verbose_name': 'Modulo compilato Bando del Dipendente', 'verbose_name_plural': 'Moduli compilati Bando dei Dipendenti'},
        ),
    ]
