# Generated by Django 2.0.3 on 2018-07-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0013_auto_20180627_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitazionebandodipendente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abilitazionebandodipendente',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='domandabando',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='domandabando',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='modulodomandabando',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modulodomandabando',
            name='modified_by',
        ),
    ]
