# Generated by Django 2.0.3 on 2018-07-11 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0014_auto_20180705_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiusuraDomandaBando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('numero_protocollo', models.CharField(blank=True, default='', max_length=32)),
                ('data_rettifica', models.DateTimeField(blank=True, help_text='Data di rettifica in caso di riapertura della domanda per modifiche', null=True)),
                ('domanda_bando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domande_peo.DomandaBando')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
