# Generated by Django 2.0.3 on 2018-07-11 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0015_chiusuradomandabando'),
    ]

    operations = [
        migrations.CreateModel(
            name='RettificaDomandaBando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data_chiusura', models.DateTimeField(blank=True, help_text='quando la domanda è stata conclusa', null=True)),
                ('numero_protocollo', models.CharField(blank=True, default='', max_length=32)),
                ('data_protocollazione', models.DateTimeField(blank=True, help_text='quando la domanda è stata protocolla/consegnata', null=True)),
                ('data_rettifica', models.DateTimeField(help_text='Data di rettifica in caso di riapertura della domanda per modifiche')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Chiusura delle Domande di partecipazione dei Dipendenti',
                'verbose_name': 'Chiusura della Domanda di partecipazione del Dipendente',
            },
        ),
        migrations.RemoveField(
            model_name='chiusuradomandabando',
            name='domanda_bando',
        ),
        migrations.AddField(
            model_name='domandabando',
            name='numero_protocollo',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='domandabando',
            name='data_chiusura',
            field=models.DateTimeField(blank=True, help_text='quando la domanda è stata conclusa, se manca significa che è stata riaperta', null=True),
        ),
        migrations.DeleteModel(
            name='ChiusuraDomandaBando',
        ),
        migrations.AddField(
            model_name='rettificadomandabando',
            name='domanda_bando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domande_peo.DomandaBando'),
        ),
    ]
