# Generated by Django 2.0.3 on 2018-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0016_auto_20180711_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='commento_punteggio',
            field=models.TextField(blank=True, default='', help_text="Il testo inserito in questo campo sarà reso visibile al dipendente dopo la chiusura del Bando e motiverà eventuali revisioni sul calcolo e l'assegnazione del punteggio"),
        ),
    ]
