# Generated by Django 2.0.3 on 2018-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0021_auto_20180724_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domandabando',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulodomandabando',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
