# Generated by Django 2.0.3 on 2018-08-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0022_auto_20180801_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domandabando',
            name='punteggio_calcolato',
            field=models.FloatField(blank=True, help_text="popolato da metodo .calcolo_punteggio_domanda, comprensivo di quello derivante dall'anzianità", null=True),
        ),
    ]
