# Generated by Django 2.2.7 on 2019-11-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0030_auto_20191017_1306'),
        ('domande_peo', '0027_auto_20181214_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='livello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_risorse_umane.LivelloPosizioneEconomica'),
        ),
    ]
