# Generated by Django 2.2.7 on 2019-11-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0028_domandabando_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='data_presa_servizio',
            field=models.DateField(blank=True, null=True, verbose_name='Data presa servizio alla data della presentazione della domanda'),
        ),
        migrations.AlterField(
            model_name='domandabando',
            name='livello',
            field=models.ForeignKey(blank=True, help_text='Livello alla data della presentazione della domanda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_risorse_umane.LivelloPosizioneEconomica'),
        ),
    ]
