# Generated by Django 2.2.7 on 2019-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0030_auto_20191111_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domandabando',
            name='data_ultima_progressione',
            field=models.DateField(blank=True, null=True, verbose_name='Data ultima progressione alla data della presentazione della domanda'),
        ),
    ]
