# Generated by Django 2.2.7 on 2019-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0031_auto_20191111_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rettificadomandabando',
            name='dump',
            field=models.TextField(blank=True, default=''),
        ),
    ]
