# Generated by Django 2.2.7 on 2019-12-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0032_rettificadomandabando_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='presa_visione_commissione',
            field=models.DateTimeField(blank=True, help_text='ultima presa visione da parte della commissione', null=True),
        ),
    ]
