# Generated by Django 2.2.7 on 2019-12-13 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domande_peo', '0033_domandabando_presa_visione_commissione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domandabando',
            old_name='presa_visione_commissione',
            new_name='presa_visione_data',
        ),
        migrations.AddField(
            model_name='domandabando',
            name='presa_visione_utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
