# Generated by Django 2.0.3 on 2018-05-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0002_dipendente_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='data_presa_servizio',
        ),
    ]
