# Generated by Django 2.0.3 on 2018-05-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0003_remove_dipendente_data_presa_servizio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='data_cessazione_contratto',
        ),
    ]
