# Generated by Django 2.0.3 on 2018-06-04 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0005_auto_20180530_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffinitaOrganizzative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Affinità Organizzativa',
                'verbose_name_plural': 'Affinità Organizzative',
            },
        ),
        migrations.AddField(
            model_name='dipendente',
            name='data_cessazione_contratto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='data_presa_servizio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='data_sicronizzazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='profilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_risorse_umane.TipoProfiloProfessionale'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='motivo_cessazione_contratto',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='affinita_organizzativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_risorse_umane.AffinitaOrganizzative'),
        ),
    ]
