# Generated by Django 2.0.3 on 2018-06-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0006_auto_20180604_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dipendente',
            old_name='data_sicronizzazione',
            new_name='data_sincronizzazione',
        ),
    ]
