# Generated by Django 2.0.3 on 2018-06-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0007_auto_20180604_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dipendente',
            old_name='data_sincronizzazione',
            new_name='data_ultima_sincronizzazione',
        ),
    ]
