# Generated by Django 2.0.3 on 2018-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0009_auto_20180604_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='codice_fiscale',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
