# Generated by Django 2.0.3 on 2018-06-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0010_auto_20180604_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelloposizioneeconomica',
            name='posizione_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestione_risorse_umane.PosizioneEconomica'),
        ),
    ]
