# Generated by Django 2.0.3 on 2018-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0011_auto_20180604_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
