# Generated by Django 2.0.3 on 2018-06-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0014_auto_20180606_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affinitaorganizzativa',
            options={'ordering': ['nome'], 'verbose_name': 'Affinità Organizzativa', 'verbose_name_plural': 'Affinità Organizzative'},
        ),
    ]
