# Generated by Django 2.0.3 on 2018-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0015_auto_20180606_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affinitaorganizzativa',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Affinita organizzativa'),
        ),
    ]
