# Generated by Django 2.0.3 on 2018-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0016_auto_20180606_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='ruolo',
            field=models.CharField(blank=True, choices=[('ND', 'ND'), ('NB', 'NB'), ('NM', 'NM'), ('D0', 'D0'), ('DC', 'DC')], default='', help_text='ND - Personale non docente.NB - ND Centro Residenziale.NM - Non docenti a tempo det.-Tesoro.D0 - Dirigenti Superiori.DC - Dirigente a contratto.', max_length=33),
        ),
    ]
