# Generated by Django 2.0.3 on 2018-06-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0017_auto_20180607_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelloposizioneeconomica',
            name='nome',
            field=models.CharField(help_text='Tradizionalmente: 1,2,3,4,5,6 ma diamo spazio ad opportune generalizzazioni', max_length=255, verbose_name='Livello Posizione Economica'),
        ),
        migrations.AlterField(
            model_name='posizioneeconomica',
            name='nome',
            field=models.CharField(help_text='Tradizionalmente: B, C, D o EP', max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tipoprofiloprofessionale',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Profilo professionale'),
        ),
    ]
