# Generated by Django 2.0.7 on 2018-07-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0018_auto_20180608_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titolostudio',
            options={'ordering': ['nome'], 'verbose_name': 'Titolo di Studio', 'verbose_name_plural': 'Titoli di Studio'},
        ),
    ]
