# Generated by Django 2.0.7 on 2018-11-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0019_auto_20180717_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dipendente',
            options={'ordering': ['cognome'], 'verbose_name': 'Dipendente', 'verbose_name_plural': 'Dipendenti'},
        ),
    ]
