# Generated by Django 2.0.3 on 2018-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0020_auto_20181117_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='data_presa_servizio_manuale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='data_ultima_progressione_manuale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
