# Generated by Django 2.0.3 on 2018-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0025_auto_20181119_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='data_cessazione_contratto_manuale',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
