# Generated by Django 2.0.6 on 2018-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0026_dipendente_data_cessazione_contratto_manuale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='data_cessazione_contratto',
            field=models.DateField(blank=True, null=True, verbose_name='Data cessazione contratto (CSA)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_presa_servizio',
            field=models.DateField(blank=True, null=True, verbose_name='Data presa servizio (CSA)'),
        ),
    ]
