# Generated by Django 2.0.3 on 2018-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0027_auto_20181127_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='disattivato',
            field=models.BooleanField(default=False, help_text='Se selezionato, esclude il dipendente da ogni operazione.'),
        ),
    ]
