# Generated by Django 2.2.3 on 2019-10-17 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0029_auto_20190131_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfferenzaOrganizzativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(max_length=255, verbose_name='Afferenza organizzativa')),
                ('descrizione', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Afferenza Organizzativa',
                'verbose_name_plural': 'Afferenza Organizzative',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='affinita_organizzativa',
        ),
        migrations.DeleteModel(
            name='AffinitaOrganizzativa',
        ),
        migrations.AddField(
            model_name='dipendente',
            name='afferenza_organizzativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_risorse_umane.AfferenzaOrganizzativa'),
        ),
    ]
