# Generated by Django 2.2.7 on 2019-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0030_auto_20191017_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='data_cessazione_contratto_manuale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_presa_servizio_manuale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_ultima_progressione_manuale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
