# Generated by Django 2.2.7 on 2019-11-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0031_avviso'),
        ('gestione_risorse_umane', '0031_auto_20191111_1124'),
    ]

    operations = [
    ]
