# Generated by Django 2.0.3 on 2018-05-30 07:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(help_text='PEO 2017', max_length=255)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('data_fine_presentazione_domande', models.DateTimeField()),
                ('descrizione', models.TextField(blank=True, default='')),
                ('ultima_progressione', models.DateField(help_text="Data dell'ultima progressione per poter partecipare alla sessione")),
                ('bando_pdf', models.FileField(blank=True, null=True, upload_to='pdf_bandi/%m-%Y/')),
                ('is_active', models.BooleanField(default=False, help_text='Se non attivo non sarà visibile al pubblico')),
            ],
            options={
                'verbose_name': 'Bando PEO',
                'verbose_name_plural': 'Bandi PEO',
            },
        ),
        migrations.CreateModel(
            name='CategorieDisabilitate_Punteggio_TitoloStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Categoria Disabilitata Punteggio Titolo Studio',
                'verbose_name_plural': 'Categorie Disabilitate Punteggio Titolo Studio',
            },
        ),
        migrations.CreateModel(
            name='DescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(help_text='Descrizione degli indicatori', max_length=255)),
                ('id_code', models.CharField(help_text='Lettera, numero o sequenza', max_length=33, verbose_name='Codice identificativo')),
                ('punteggio_max', models.PositiveIntegerField(blank=True, default=0, help_text='Punteggio massimo, se 0 non vi è soglia limite')),
                ('note', models.TextField(blank=True, default='', help_text='es. Non saranno oggetto di valutazione di sorveglienza/vigilanza antifumo...')),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Descrizione Indicatore',
                'verbose_name_plural': 'Descrizioni Indicatori',
            },
        ),
        migrations.CreateModel(
            name='IndicatorePonderato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(help_text='Indicatore Ponderato (art.82 CCNL)', max_length=255)),
                ('id_code', models.CharField(help_text='Lettera, numero o sequenza', max_length=33, verbose_name='Codice identificativo')),
                ('calcolo_punteggio_automatico', models.BooleanField(help_text='es. Arricchimento professionale o Qualità delle prestazioni individuali. Se disabilitato richiede valutazione manuale e non richiede la definizione di indicatori di valutazione o pesi/punteggi a sistema')),
                ('note', models.TextField(blank=True, default='', help_text="es. Solo ai candidati in possesso di un'anzianità di servizio di almeno 3 anni...")),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Indicatore Ponderato',
                'verbose_name_plural': 'Indicatori Ponderati',
            },
        ),
        migrations.CreateModel(
            name='ModuloInserimentoCampi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CharField', 'caratteri'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('SelectField', 'selezione multipla'), ('DateField', 'data'), ('DateTimeField', 'data con orario')], max_length=33)),
                ('is_required', models.BooleanField(default=True)),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Modulo Inserimento Campi',
                'verbose_name_plural': 'Modulo Inserimento Campi',
            },
        ),
        migrations.CreateModel(
            name='Punteggio_Anzianita_Servizio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unita_temporale', models.CharField(choices=[('h', 'ore'), ('d', 'giorni'), ('m', 'mesi'), ('y', 'anni')], default='m', max_length=1, verbose_name='Unita temporale di riferimento')),
                ('punteggio', models.FloatField(help_text="punteggio attribuito per ogni anno/mese di servizio. Deve essere un numero positivo moltiplicabile per la  durata dichiarata dall'utente istante", validators=[django.core.validators.MinValueValidator(0.01)])),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio per Anzianità di servizio',
                'verbose_name_plural': 'Punteggi per Anzianità di servizio',
            },
        ),
        migrations.CreateModel(
            name='Punteggio_DescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', help_text='Descrizione degli indicatorinome del titolo presentato', max_length=255)),
                ('punteggio', models.FloatField()),
                ('note', models.CharField(blank=True, default='', help_text='Descrizione', max_length=255)),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio per Categoria',
                'verbose_name_plural': 'Punteggi per Categoria',
            },
        ),
        migrations.CreateModel(
            name='Punteggio_DescrizioneIndicatore_TimeDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', help_text='Descrizione degli indicatorinome del titolo presentato', max_length=255)),
                ('unita_temporale', models.CharField(choices=[('h', 'ore'), ('d', 'giorni'), ('m', 'mesi'), ('y', 'anni')], default='m', max_length=1, verbose_name='Unita temporale di riferimento')),
                ('durata_minima', models.PositiveIntegerField(help_text="quantità riferita all'unità temporale di riferimento")),
                ('durata_massima', models.PositiveIntegerField(help_text="es. 'oltre 16 ore' immettere 17 ore")),
                ('punteggio', models.FloatField()),
                ('note', models.CharField(blank=True, default='', help_text='Descrizione', max_length=255)),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio per durata temporale',
                'verbose_name_plural': 'Punteggi per durata temporale',
            },
        ),
        migrations.CreateModel(
            name='Punteggio_TitoloStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('punteggio', models.PositiveIntegerField()),
                ('cumulabile', models.BooleanField(default=False, help_text='Indica se più titoli equivalenti possano essere cumulati in una unica progressione')),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio per Titolo di Studio',
                'verbose_name_plural': 'Punteggi per Titolo di Studio',
            },
        ),
        migrations.CreateModel(
            name='PunteggioMax_DescrizioneIndicatore_PosEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_max', models.PositiveIntegerField(help_text='es. max 10 punti per ctg EP-D-C, max 12 punti per ctg B')),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio Max Descrizione Indicatore per Categoria',
                'verbose_name_plural': 'Punteggi Max Descrizione Indicatore per Categoria',
            },
        ),
        migrations.CreateModel(
            name='PunteggioMax_IndicatorePonderato_PosEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_max', models.PositiveIntegerField(help_text='es. EP 20, D 20, C 20, B 25')),
                ('ordinamento', models.PositiveIntegerField(help_text="posizione nell'ordinamento")),
            ],
            options={
                'verbose_name': 'Punteggio Max Indicatore Ponderato per Categoria',
                'verbose_name_plural': 'Punteggi Max Indicatore Ponderato per Categorie',
            },
        ),
    ]
