# Generated by Django 2.0.3 on 2018-05-30 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_peo', '0001_initial'),
        ('gestione_risorse_umane', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggiomax_indicatoreponderato_poseconomica',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggiomax_indicatoreponderato_poseconomica_related+', related_query_name='created-gestione_peo_punteggiomax_indicatoreponderato_poseconomicas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggiomax_indicatoreponderato_poseconomica',
            name='indicatore_ponderato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.IndicatorePonderato'),
        ),
        migrations.AddField(
            model_name='punteggiomax_indicatoreponderato_poseconomica',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggiomax_indicatoreponderato_poseconomica_related+', related_query_name='modified-gestione_peo_punteggiomax_indicatoreponderato_poseconomicas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggiomax_indicatoreponderato_poseconomica',
            name='posizione_economica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggiomax_descrizioneindicatore_poseconomica_related+', related_query_name='created-gestione_peo_punteggiomax_descrizioneindicatore_poseconomicas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore', verbose_name='Indicatore titolo'),
        ),
        migrations.AddField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggiomax_descrizioneindicatore_poseconomica_related+', related_query_name='modified-gestione_peo_punteggiomax_descrizioneindicatore_poseconomicas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='posizione_economica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='punteggio_titolostudio',
            name='bando',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando'),
        ),
        migrations.AddField(
            model_name='punteggio_titolostudio',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggio_titolostudio_related+', related_query_name='created-gestione_peo_punteggio_titolostudios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_titolostudio',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggio_titolostudio_related+', related_query_name='modified-gestione_peo_punteggio_titolostudios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_titolostudio',
            name='titolo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.TitoloStudio'),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggio_descrizioneindicatore_timedelta_related+', related_query_name='created-gestione_peo_punteggio_descrizioneindicatore_timedeltas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore', verbose_name='Descrizione Indicatore'),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggio_descrizioneindicatore_timedelta_related+', related_query_name='modified-gestione_peo_punteggio_descrizioneindicatore_timedeltas+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='pos_eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggio_descrizioneindicatore_related+', related_query_name='created-gestione_peo_punteggio_descrizioneindicatores+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore',
            name='descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore', verbose_name='Descrizione Indicatore'),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggio_descrizioneindicatore_related+', related_query_name='modified-gestione_peo_punteggio_descrizioneindicatores+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore',
            name='pos_eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='punteggio_anzianita_servizio',
            name='bando',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando'),
        ),
        migrations.AddField(
            model_name='punteggio_anzianita_servizio',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_punteggio_anzianita_servizio_related+', related_query_name='created-gestione_peo_punteggio_anzianita_servizios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_anzianita_servizio',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_punteggio_anzianita_servizio_related+', related_query_name='modified-gestione_peo_punteggio_anzianita_servizios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punteggio_anzianita_servizio',
            name='posizione_economica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='moduloinserimentocampi',
            name='descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore'),
        ),
        migrations.AddField(
            model_name='indicatoreponderato',
            name='bando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando'),
        ),
        migrations.AddField(
            model_name='indicatoreponderato',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_indicatoreponderato_related+', related_query_name='created-gestione_peo_indicatoreponderatos+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatoreponderato',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_indicatoreponderato_related+', related_query_name='modified-gestione_peo_indicatoreponderatos+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_descrizioneindicatore_related+', related_query_name='created-gestione_peo_descrizioneindicatores+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='indicatore_ponderato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.IndicatorePonderato'),
        ),
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_descrizioneindicatore_related+', related_query_name='modified-gestione_peo_descrizioneindicatores+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='bando',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando'),
        ),
        migrations.AddField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_categoriedisabilitate_punteggio_titolostudio_related+', related_query_name='created-gestione_peo_categoriedisabilitate_punteggio_titolostudios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_categoriedisabilitate_punteggio_titolostudio_related+', related_query_name='modified-gestione_peo_categoriedisabilitate_punteggio_titolostudios+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='posizione_economica',
            field=models.ManyToManyField(blank=True, to='gestione_risorse_umane.PosizioneEconomica'),
        ),
        migrations.AddField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='titolo_studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Punteggio_TitoloStudio'),
        ),
        migrations.AddField(
            model_name='bando',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_bando_related+', related_query_name='created-gestione_peo_bandos+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bando',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_bando_related+', related_query_name='modified-gestione_peo_bandos+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='indicatoreponderato',
            unique_together={('bando', 'id_code')},
        ),
    ]
