# Generated by Django 2.0.3 on 2018-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0003_auto_20180530_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Se attivo sarà Bando di riferimento per calcolo AD USO INTERNO per la valutazione di idoneità per i dipendenti'),
        ),
    ]
