# Generated by Django 2.0.3 on 2018-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0004_auto_20180530_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='collaudo',
            field=models.BooleanField(default=True, help_text='Se selezionato sarà visibile ai soli utenti STAFF per opportuni collaudi'),
        ),
        migrations.AlterField(
            model_name='bando',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se attivo sarà Bando di riferimento per calcolo AD USO INTERNO per la valutazione di idoneità per i dipendenti'),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('DateTimeField', 'data con orario'), ('FileField', 'allegato pdf')], max_length=33),
        ),
    ]
