# Generated by Django 2.0.3 on 2018-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0005_auto_20180530_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='collaudo',
            field=models.BooleanField(default=True, help_text='Se selezionato sarà visibile ai soli utenti afferenti al gruppo STAFF'),
        ),
    ]
