# Generated by Django 2.0.3 on 2018-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0006_auto_20180530_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se attivo sarà di riferimento per la valutazione delle idoneità AD USO INTERNO: azioni e filtri backend.', verbose_name='redazione'),
        ),
    ]
