# Generated by Django 2.0.3 on 2018-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0007_auto_20180530_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduloinserimentocampi',
            name='aiuto',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
