# Generated by Django 2.0.3 on 2018-06-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0008_moduloinserimentocampi_aiuto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduloinserimentocampi',
            options={'ordering': ('ordinamento',), 'verbose_name': 'Modulo Inserimento Campi', 'verbose_name_plural': 'Modulo Inserimento Campi'},
        ),
    ]
