# Generated by Django 2.0.3 on 2018-06-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0010_clausolebando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausolebando',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visibile agli utenti'),
        ),
    ]
