# Generated by Django 2.0.3 on 2018-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0013_auto_20180604_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedisabilitate_punteggio_titolostudio',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='clausolebando',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='descrizioneindicatore',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='indicatoreponderato',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('DateTimeField', 'data con orario'), ('FileField', 'allegato pdf')], max_length=33),
        ),
        migrations.AlterField(
            model_name='punteggio_anzianita_servizio',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='punteggio_descrizioneindicatore',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='punteggio_titolostudio',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
        migrations.AlterField(
            model_name='punteggiomax_indicatoreponderato_poseconomica',
            name='ordinamento',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento"),
        ),
    ]
