# Generated by Django 2.0.3 on 2018-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0014_auto_20180604_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('DateTimeField', 'data con orario'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox')], max_length=33),
        ),
    ]
