# Generated by Django 2.0.3 on 2018-06-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0015_auto_20180607_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clausolebando',
            old_name='descrizione',
            new_name='corpo_del_testo',
        ),
    ]
