# Generated by Django 2.0.3 on 2018-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0016_auto_20180607_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('DateTimeField', 'data con orario'), ('StartDateField', 'data inizio'), ('StartDateTimeField', 'data inizio con orario'), ('EndDateField', 'data fine + checkbox "fino ad oggi"'), ('EndDateTimeField', 'data fine con orario + checkbox "fino ad oggi"'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox')], max_length=33),
        ),
    ]
