# Generated by Django 2.0.3 on 2018-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0017_auto_20180608_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('StartDateField', 'data inizio'), ('EndDateField', 'data fine + checkbox "fino ad oggi"'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox')], max_length=33),
        ),
    ]
