# Generated by Django 2.0.3 on 2018-06-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0018_auto_20180608_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clausolebando',
            options={'ordering': ('ordinamento',), 'verbose_name': 'Clausola Bando', 'verbose_name_plural': 'Clausole Bando'},
        ),
    ]
