# Generated by Django 2.0.3 on 2018-07-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0026_auto_20180705_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatoreponderato',
            name='calcolo_punteggio_automatico',
        ),
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='calcolo_punteggio_automatico',
            field=models.BooleanField(default=False, help_text='es. Arricchimento professionale o Qualità delle prestazioni individuali. Se disabilitato richiede valutazione manuale e non richiede la definizione di indicatori di valutazione o pesi/punteggi a sistema'),
        ),
    ]
