# Generated by Django 2.0.3 on 2018-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0027_auto_20180711_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descrizioneindicatore',
            name='calcolo_punteggio_automatico',
            field=models.BooleanField(default=False, help_text='Se disabilitato richiede valutazione manuale e non richiede la definizione di indicatori di valutazione o pesi/punteggi a sistema'),
        ),
    ]
