# Generated by Django 2.0.3 on 2018-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0030_auto_20180712_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bando',
            old_name='agevolazione_dipendenti_bloccati_anni',
            new_name='agevolazione_soglia_anni',
        ),
        migrations.RemoveField(
            model_name='bando',
            name='agevolazione_dipendenti_bloccati_fattore_moltiplicazione',
        ),
        migrations.AddField(
            model_name='bando',
            name='agevolazione_fatmol',
            field=models.IntegerField(default=1, help_text="Fattore di moltiplicazione del punteggio relativo all'anzianità di servizio nel caso di permanenza maggiore o uguale alla soglia stabilita.Serve per agevolare i dipendenti che da N anni non superano la progressione", verbose_name='Fattore moltiplicazione per bonus punteggio anzianità'),
        ),
        migrations.AlterField(
            model_name='descrizioneindicatore',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Se attivo la domanda non potrà essere presentata senza la presenza di questo Indicatore.'),
        ),
    ]
