# Generated by Django 2.0.3 on 2018-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0032_auto_20180712_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='operatore',
            field=models.CharField(choices=[('x', 'moltiplicatore'), ('a', 'assegnazione')], default='a', help_text="Operatore che determina l'assegnazione", max_length=1, verbose_name='Operatore da applicare al punteggio'),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('_TitoloStudioField', 'selezione titolo di studio'), ('DateField', 'data'), ('StartEndDateField', 'data inizio + data fine + checkbox "fino ad oggi"'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox'), ('CustomSelectBoxField', 'menu a tendina'), ('CustomRadioBoxField', 'serie di opzioni'), ('ProtocolloField', 'protocollo (numero + data)'), ('DurataInOreField', 'durata in ore')], max_length=33),
        ),
        migrations.AlterField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='punteggio',
            field=models.FloatField(help_text="In base all'operatore selezionato viene assegnato all'intervallo temporale o a singole ore/mesi/anni dell'intervallo"),
        ),
    ]
