# Generated by Django 2.0.3 on 2018-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0033_auto_20180713_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='valore',
            field=models.CharField(blank=True, default='', help_text="compilare esclusivamente se si sceglie 'Menu a tendina' oppure 'Serie di Opzioni' separati da ';'.", max_length=255, verbose_name='Lista di Valori'),
        ),
    ]
