# Generated by Django 2.0.7 on 2018-07-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0018_auto_20180608_1013'),
        ('gestione_peo', '0035_auto_20180715_0038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieDisabilitate_Punteggio_TitoloStudio',
            new_name='CategorieDisabilitate_TitoloStudio',
        ),
        migrations.AlterField(
            model_name='categoriedisabilitate_titolostudio',
            name='titolo_studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.TitoloStudio'),
        ),
        migrations.AlterField(
            model_name='clausolebando',
            name='titolo',
            field=models.CharField(help_text='Titolo clausola (es: Privacy...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='descrizioneindicatore',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Se attivo la domanda non potrà essere presentata senza la presenza di questo Indicatore.', verbose_name='Inserimento in domanda obbligatorio'),
        ),
    ]
