# Generated by Django 2.0.3 on 2018-07-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0036_auto_20180717_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatoreponderato',
            options={'ordering': ['bando', 'nome'], 'verbose_name': 'Indicatore Ponderato', 'verbose_name_plural': 'Indicatori Ponderati'},
        ),
        migrations.RemoveField(
            model_name='descrizioneindicatore',
            name='punteggio_max',
        ),
    ]
