# Generated by Django 2.0.3 on 2018-07-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0039_auto_20180724_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatoreponderato',
            name='add_punteggio_anzianita',
            field=models.BooleanField(default=False, help_text="Se attivo, al punteggio derivante dagli inserimenti del Dipendente, verrà sommato il punteggio relativo all'anzianità di servizio (Unical), rispettando sempre il max ottenibile", verbose_name='Somma Punteggio Anzianità Servizio'),
        ),
    ]
