# Generated by Django 2.0.6 on 2018-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0040_indicatoreponderato_add_punteggio_anzianita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descrizioneindicatore',
            name='calcolo_punteggio_automatico',
            field=models.BooleanField(default=True, help_text='Se disabilitato richiede valutazione manuale e non richiede la definizione di indicatori di valutazione o pesi/punteggi a sistema'),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('PunteggioFloatField', 'punteggio (numero con virgola)'), ('_TitoloStudioField', 'selezione titolo di studio'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox'), ('CustomSelectBoxField', 'menu a tendina'), ('CustomRadioBoxField', 'serie di opzioni'), ('ProtocolloField', 'protocollo (numero + data)'), ('DateField', 'data'), ('StartEndDateField', 'intervallo date IN RANGE Bando'), ('OutStartEndDateField', 'intervallo date OUT OF RANGE Bando'), ('DurataComeInteroField', 'durata in anni/mesi/ore'), ('DataLowerThanBandoField', 'data non superiore al bando')], max_length=33),
        ),
    ]
