# Generated by Django 2.0.3 on 2018-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0041_auto_20180731_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CharField', 'caratteri'), ('TextField', 'descrizione lunga'), ('IntegerField', 'numero intero'), ('FloatField', 'numero con virgola'), ('PunteggioFloatField', 'punteggio (numero con virgola)'), ('_TitoloStudioField', 'selezione titolo di studio (con calcolo punteggio)'), ('FileField', 'allegato pdf'), ('CheckBoxField', 'checkbox'), ('CustomSelectBoxField', 'menu a tendina'), ('CustomRadioBoxField', 'serie di opzioni'), ('ProtocolloField', 'protocollo (numero + data)'), ('DateField', 'data'), ('StartEndDateField', 'intervallo date IN RANGE Bando'), ('OutStartEndDateField', 'intervallo date OUT OF RANGE Bando'), ('DurataComeInteroField', 'durata in anni/mesi/ore'), ('DataLowerThanBandoField', 'data non superiore al bando')], max_length=33),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='valore',
            field=models.CharField(blank=True, default='', help_text="Viene considerato solo se si sceglie 'Menu a tendina' oppure 'Serie di Opzioni'. (Es: valore1;valore2;valore3...)", max_length=255, verbose_name='Lista di Valori'),
        ),
    ]
