# Generated by Django 2.0.3 on 2018-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0042_auto_20180801_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduloinserimentocampi',
            options={},
        ),
        migrations.RemoveField(
            model_name='bando',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bando',
            name='redazione',
            field=models.BooleanField(default=True, help_text='Se attivo sarà di riferimento per la valutazione delle idoneità AD USO INTERNO: azioni e filtri backend.'),
        ),
        migrations.AlterField(
            model_name='bando',
            name='nome',
            field=models.CharField(help_text='Procedura Elettronica On-line A.A.2017', max_length=255),
        ),
    ]
