# Generated by Django 2.0.3 on 2018-09-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0043_auto_20180806_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduloinserimentocampi',
            options={'ordering': ('ordinamento',), 'verbose_name': 'Modulo di inserimento', 'verbose_name_plural': 'Moduli di inserimento'},
        ),
    ]
