# Generated by Django 2.0.3 on 2018-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0044_auto_20180906_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggiomax_descrizioneindicatore_poseconomica',
            name='punteggio_max',
            field=models.FloatField(help_text='es. max 10 punti per ctg EP-D-C, max 12 punti per ctg B'),
        ),
    ]
