# Generated by Django 2.0.3 on 2018-09-21 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0019_auto_20180717_0127'),
        ('gestione_peo', '0049_auto_20180917_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punteggio_SubDescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('punteggio', models.FloatField()),
                ('note', models.CharField(blank=True, default='', help_text='Descrizione', max_length=255)),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('pos_eco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Punteggio per Categoria',
                'verbose_name_plural': 'Punteggi per Categoria',
            },
        ),
        migrations.CreateModel(
            name='Punteggio_SubDescrizioneIndicatore_TimeDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('unita_temporale', models.CharField(choices=[('h', 'ore'), ('d', 'giorni'), ('m', 'mesi'), ('y', 'anni')], default='m', max_length=1, verbose_name='Unita temporale di riferimento')),
                ('durata_minima', models.PositiveIntegerField(help_text="quantità riferita all'unità temporale di riferimento")),
                ('durata_massima', models.PositiveIntegerField(help_text="es. 'oltre 16 ore' immettere 17 ore")),
                ('punteggio', models.FloatField(help_text="In base all'operatore selezionato viene assegnato all'intervallo temporale o a singole ore/mesi/anni dell'intervallo")),
                ('operatore', models.CharField(choices=[('x', 'moltiplicatore'), ('a', 'assegnazione'), ('+', 'addizione'), ('/', 'divisione'), ('-', 'sottrazione')], default='a', help_text="Operatore che determina l'assegnazione", max_length=1, verbose_name='Operatore da applicare al punteggio')),
                ('note', models.CharField(blank=True, default='', help_text='Descrizione', max_length=255)),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('pos_eco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Punteggio per durata temporale',
                'verbose_name_plural': 'Punteggi per durata temporale',
            },
        ),
        migrations.CreateModel(
            name='PunteggioMax_SubDescrizioneIndicatore_PosEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio_max', models.FloatField(help_text='es. max 10 punti per ctg EP-D-C, max 12 punti per ctg B')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('posizione_economica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Punteggio Max Sub Descrizione Indicatore per Categoria',
                'verbose_name_plural': 'Punteggi Max Sub Descrizione Indicatore per Categoria',
            },
        ),
        migrations.CreateModel(
            name='SubDescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(help_text='Sotto-livello Descrizione degli indicatori', max_length=255)),
                ('id_code', models.CharField(help_text='Lettera, numero o sequenza', max_length=33, verbose_name='Codice identificativo')),
                ('is_required', models.BooleanField(default=False, help_text='Se attivo la domanda non potrà essere presentata senza la presenza di questo Indicatore.', verbose_name='Inserimento in domanda obbligatorio')),
                ('note', models.TextField(blank=True, default='', help_text='es. Non saranno oggetto di valutazione di sorveglienza/vigilanza antifumo...')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore')),
            ],
            options={
                'verbose_name': 'Sotto-livello Descrizione Indicatore',
                'verbose_name_plural': 'Sotto-livelli Descrizione Indicatore',
                'ordering': ['descrizione_indicatore', 'ordinamento'],
            },
        ),
        migrations.AlterField(
            model_name='punteggio_descrizioneindicatore',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='punteggiomax_subdescrizioneindicatore_poseconomica',
            name='sub_descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.SubDescrizioneIndicatore', verbose_name='Sub Descrizione Indicatore titolo'),
        ),
        migrations.AddField(
            model_name='punteggio_subdescrizioneindicatore_timedelta',
            name='sub_descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.SubDescrizioneIndicatore', verbose_name='Sub Descrizione Indicatore'),
        ),
        migrations.AddField(
            model_name='punteggio_subdescrizioneindicatore',
            name='sub_descrizione_indicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.SubDescrizioneIndicatore', verbose_name='Sub Descrizione Indicatore'),
        ),
    ]
