# Generated by Django 2.0.3 on 2018-09-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0051_auto_20180924_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdescrizioneindicatore',
            name='is_required',
        ),
    ]
