# Generated by Django 2.0.3 on 2018-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0052_remove_subdescrizioneindicatore_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='non_cancellabile',
            field=models.BooleanField(default=False, help_text="Se attivo, dalla domanda non potranno essere eliminati i relativi moduli compilati e l'intera domanda non potrà essere distrutta", verbose_name='Impossibile eliminare i moduli compilati nella domanda'),
        ),
    ]
