# Generated by Django 2.0.3 on 2018-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0053_descrizioneindicatore_non_cancellabile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='protocollo_cod_titolario',
            field=models.CharField(blank=True, choices=[('9095', '7.1')], max_length=12, null=True, verbose_name='Codice titolario'),
        ),
        migrations.AddField(
            model_name='bando',
            name='protocollo_fascicolo_numero',
            field=models.CharField(default='3', max_length=12, verbose_name='Fascicolo numero'),
        ),
    ]
