# Generated by Django 2.0.3 on 2018-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0054_auto_20181022_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausolebando',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='allegati_clausola_partecipaziopne/%m-%Y/'),
        ),
    ]
