# Generated by Django 2.0.3 on 2018-11-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0055_clausolebando_allegato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bando',
            options={'verbose_name': 'Bando', 'verbose_name_plural': 'Bandi'},
        ),
    ]
