# Generated by Django 2.0.3 on 2018-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0056_auto_20181103_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='email_avvenuto_completamento',
            field=models.BooleanField(default=False, help_text='Se selezionato verrà inviata una email di avvenuta trasmissione della domanda'),
        ),
        migrations.AddField(
            model_name='bando',
            name='pubblica_punteggio',
            field=models.BooleanField(default=False, help_text='Rende visibile il punteggio calcolato agli utenti'),
        ),
    ]
