# Generated by Django 2.0.3 on 2018-11-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0057_bando_accettazione_clausole_text'),
        ('gestione_peo', '0057_auto_20181112_1013'),
    ]

    operations = [
    ]
