# Generated by Django 2.0.3 on 2018-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0058_merge_20181112_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bando',
            name='bando_pdf',
        ),
        migrations.AddField(
            model_name='bando',
            name='bando_url',
            field=models.CharField(blank=True, help_text='URL della risorsa web con le specifiche del Bando', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bando',
            name='accettazione_clausole_text',
            field=models.TextField(blank=True, help_text='es. Dichiaro di aver preso visione...', null=True, verbose_name='Testo Accettazione Clausole'),
        ),
    ]
