# Generated by Django 2.0.7 on 2018-11-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0061_auto_20181115_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='protocollo_cod_titolario',
            field=models.CharField(blank=True, choices=[('3', '3')], max_length=12, null=True, verbose_name='Codice titolario'),
        ),
    ]
