# Generated by Django 2.0.6 on 2018-11-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0062_auto_20181116_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='protocollo_cod_titolario',
            field=models.CharField(blank=True, choices=[('9095', '7.1')], max_length=12, null=True, verbose_name='Codice titolario'),
        ),
    ]
