# Generated by Django 2.0.3 on 2019-01-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0063_auto_20181117_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CustomFileField', 'Allegato PDF'), ('AnnoInRangeOfCarrieraField', 'Anno singolo IN RANGE of bando'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DateInRangeComplexField', 'Data inizio e Data fine IN RANGE of bando'), ('DateInRangeInCorsoComplexField', "Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('DateOutOfRangeComplexField', 'Data inizio e Data fine OUT OF RANGE of bando'), ('DataLowerThanBandoField', 'Data singola IN RANGE of bando'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('PunteggioFloatField', 'Punteggio (numero con virgola)'), ('SubDescrizioneIndicatoreField', 'Selezione sotto-categorie DescrizioneIndicatore'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('TitoloStudioField', 'Titoli di studio')], help_text='I campi contrassegnati da asterisco (*) vengono validati tenendo conto delle specifiche del Bando, pertanto possono influire sul calcolo del punteggio', max_length=33),
        ),
    ]
