# Generated by Django 2.0.3 on 2019-01-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0028_dipendente_disattivato'),
        ('gestione_peo', '0064_auto_20190118_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDisabilitate_DescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore')),
                ('posizione_economica', models.ManyToManyField(blank=True, to='gestione_risorse_umane.PosizioneEconomica')),
            ],
            options={
                'verbose_name_plural': 'Categorie Disabilitate Descrizione Indicatore',
                'verbose_name': 'Categoria Disabilitata Descrizione Indicatore',
            },
        ),
    ]
