# Generated by Django 2.0.3 on 2019-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0065_categoriedisabilitate_descrizioneindicatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='descrizioneindicatore',
            name='univoco',
            field=models.BooleanField(default=False, help_text="Se attivo, impedisce l'inserimento multiplo.", verbose_name='Inserimento multiplo disabilitato'),
        ),
        migrations.AlterField(
            model_name='bando',
            name='collaudo',
            field=models.BooleanField(default=False, help_text='Se selezionato sarà visibile ai soli utenti afferenti al gruppo STAFF'),
        ),
        migrations.AlterField(
            model_name='bando',
            name='redazione',
            field=models.BooleanField(default=False, help_text='Se attivo sarà di riferimento per la valutazione delle idoneità AD USO INTERNO: azioni e filtri backend.'),
        ),
    ]
