# Generated by Django 2.0.3 on 2019-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0068_auto_20190201_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausolebando',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='allegati_clausola_partecipazione/%m-%Y/'),
        ),
    ]
