# Generated by Django 2.0.3 on 2019-02-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0069_auto_20190201_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuoliDisabilitati_DescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('ND', 'ND - Personale non docente'), ('DC', 'DC - Dirigente a contratto'), ('NB', 'NB - ND Centro Residenziale'), ('D0', 'D0 - Dirigenti Superiori'), ('NM', 'NM - Non docenti a tempo det.-Tesoro'), ('NG', 'NG - Addetti ufficio stampa'), ('PO', 'PO - Professori Ordinari'), ('PA', 'PA - Professori Associati'), ('RU', 'RU - Ricercatori Universitari'), ('RM', 'RM - Ricercatori a tempo det-Tesoro'), ('RD', 'RD - Ricercatori Legge 240/10 - t.det.')], max_length=50)),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.DescrizioneIndicatore')),
            ],
            options={
                'verbose_name': 'Categoria Disabilitata Descrizione Indicatore',
                'verbose_name_plural': 'Categorie Disabilitate Descrizione Indicatore',
            },
        ),
    ]
