# Generated by Django 2.0.3 on 2019-02-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0070_ruolidisabilitati_descrizioneindicatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruolidisabilitati_descrizioneindicatore',
            options={'verbose_name': 'Ruolo Disabilitato Descrizione Indicatore', 'verbose_name_plural': 'Ruoli Disabilitati Descrizione Indicatore'},
        ),
    ]
