# Generated by Django 2.0.3 on 2019-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0078_auto_20190204_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='protocollo_template',
            field=models.TextField(blank=True, default='', help_text='Template XML che descrive il flusso'),
        ),
    ]
