# Generated by Django 2.0.13 on 2019-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0082_auto_20190626_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='tipo',
            field=models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('PEO_BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('PEO_BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('PEO_AnnoInRangeOfCarrieraField', '_PEO_  Anno singolo IN RANGE of bando'), ('PEO_DateInRangeComplexField', '_PEO_  Data inizio e Data fine IN RANGE of bando'), ('PEO_DateInRangeInCorsoComplexField', "_PEO_  Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('PEO_DateOutOfRangeComplexField', '_PEO_  Data inizio e Data fine OUT OF RANGE of bando'), ('PEO_DataLowerThanBandoField', '_PEO_  Data singola IN RANGE of bando'), ('PEO_ProtocolloField', '_PEO_  Protocollo (tipo/numero/data)'), ('PEO_PunteggioFloatField', '_PEO_  Punteggio (numero con virgola)'), ('PEO_SubDescrizioneIndicatoreField', '_PEO_  Selezione sotto-categorie DescrizioneIndicatore'), ('PEO_TitoloStudioField', '_PEO_  Titoli di studio'), ('PEO_DateStartEndComplexField', '_PEO_ Data inizio e Data fine')], max_length=33),
        ),
    ]
