# Generated by Django 2.0.13 on 2019-06-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0084_auto_20190627_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduloinserimentocampi',
            old_name='nome',
            new_name='name',
        ),
    ]
