# Generated by Django 2.0.3 on 2019-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0086_auto_20190628_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='protocollo_cod_titolario',
            field=models.CharField(blank=True, choices=[('9095', '7.1'), ('9099', '7.5')], max_length=12, null=True, verbose_name='Codice titolario'),
        ),
    ]
