# Generated by Django 2.2.7 on 2019-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0087_auto_20190702_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduloinserimentocampi',
            options={'ordering': ('ordinamento',), 'verbose_name': 'Modulo di inserimento', 'verbose_name_plural': 'Moduli di inserimento'},
        ),
    ]
