# Generated by Django 2.2.7 on 2019-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0091_avvisobando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avvisobando',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='avvisi_bando/%m-%Y/'),
        ),
    ]
