# Generated by Django 2.2.7 on 2019-11-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione_peo', '0092_auto_20191111_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissioneGiudicatrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('denominazione', models.CharField(default='', max_length=255)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('accettazione_clausole_text', models.TextField(blank=True, help_text='es. Dichiaro di aver preso visione...', null=True, verbose_name='Testo Accettazione Clausole')),
                ('is_active', models.BooleanField(help_text='Attiva')),
                ('bando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_commissionegiudicatrice_related+', related_query_name='created-gestione_peo_commissionegiudicatrices+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_commissionegiudicatrice_related+', related_query_name='modified-gestione_peo_commissionegiudicatrices+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commissione giudicatrice',
                'verbose_name_plural': 'Commissioni giudicatrici',
            },
        ),
        migrations.CreateModel(
            name='ClausoleCommissioneGiudicatrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titolo', models.CharField(help_text='Titolo clausola (es: Privacy...)', max_length=255)),
                ('corpo_del_testo', models.TextField(help_text='es. La partecipazione alla Commissione comporta...')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('allegato', models.FileField(blank=True, null=True, upload_to='allegati_clausola_partecipazione/commissioni/%m-%Y/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visibile agli utenti')),
                ('commissione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.CommissioneGiudicatrice')),
            ],
            options={
                'verbose_name': 'Clausola Commissione Giudicatrice',
                'verbose_name_plural': 'Clausole Commissione Giudicatrice',
                'ordering': ('ordinamento',),
            },
        ),
        migrations.CreateModel(
            name='CommissioneGiudicatriceUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ruolo', models.CharField(blank=True, max_length=255, null=True)),
                ('clausole_accettate', models.BooleanField(default=False, help_text='Ha accettato le clausole per la partecipazione alla commissione')),
                ('is_active', models.BooleanField(help_text='Attivo')),
                ('commissione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.CommissioneGiudicatrice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created-gestione_peo_commissionegiudicatriceusers_related+', related_query_name='created-gestione_peo_commissionegiudicatriceuserss+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified-gestione_peo_commissionegiudicatriceusers_related+', related_query_name='modified-gestione_peo_commissionegiudicatriceuserss+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utente Commissione Giudicatrice',
                'verbose_name_plural': 'Utenti Commissioni Giudicatrici',
                'unique_together': {('commissione', 'user')},
            },
        ),
    ]
