# Generated by Django 2.2.9 on 2021-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0093_clausolecommissionegiudicatrice_commissionegiudicatrice_commissionegiudicatriceusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='data_validita_titoli_inizio',
            field=models.DateField(blank=True, help_text='Data fino alla quale i titoli sono accettati', null=True, verbose_name='Data inizio validità titoli'),
        ),
    ]
