# Generated by Django 2.2.9 on 2021-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0094_auto_20210117_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='data_validita_titoli_inizio',
            field=models.DateField(blank=True, help_text='Data dalla quale i titoli sono accettati. Se vuoto, viene considerata  la data di ultima progressione.', null=True, verbose_name='Data inizio validità titoli'),
        ),
    ]
