# Generated by Django 2.2.9 on 2021-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0095_auto_20210117_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='considera_ultima_progressione',
            field=models.BooleanField(default=False, help_text='Se selezionato, verranno confrontate le date di ultima_progressione e data_validita_titoli_inizio e scelta la più recente'),
        ),
    ]
