# Generated by Django 2.2.9 on 2021-10-21 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0032_merge_20191111_1137'),
        ('gestione_peo', '0097_auto_20210117_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='field_type',
            field=models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('PEO_BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('PEO_BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomEmailField', 'E-mail'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('PEO_AnnoInRangeOfCarrieraField', '_PEO_  Anno singolo IN RANGE of bando'), ('PEO_DateInRangeComplexField', '_PEO_  Data inizio e Data fine IN RANGE of bando'), ('PEO_DateInRangeInCorsoComplexField', "_PEO_  Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('PEO_DateOutOfRangeComplexField', '_PEO_  Data inizio e Data fine OUT OF RANGE of bando'), ('PEO_DataLowerThanBandoField', '_PEO_  Data singola IN RANGE of bando'), ('PEO_ProtocolloField', '_PEO_  Protocollo (tipo/numero/data)'), ('PEO_PunteggioFloatField', '_PEO_  Punteggio (numero con virgola)'), ('PEO_SubDescrizioneIndicatoreField', '_PEO_  Selezione sotto-categorie DescrizioneIndicatore'), ('PEO_TitoloStudioField', '_PEO_  Titoli di studio'), ('PEO_DateStartEndComplexField', '_PEO_ Data inizio e Data fine')], max_length=100),
        ),
        migrations.CreateModel(
            name='Punteggio_Anzianita_Servizio_Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unita_temporale', models.CharField(choices=[('h', 'ore'), ('d', 'giorni'), ('m', 'mesi'), ('y', 'anni')], default='m', max_length=1, verbose_name='Unita temporale di riferimento')),
                ('punteggio', models.FloatField(help_text="punteggio attribuito per ogni anno/mese di servizio. Deve essere un numero positivo moltiplicabile per la  durata dichiarata dall'utente istante", validators=[django.core.validators.MinValueValidator(0.01)])),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('bando', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.Bando')),
                ('posizione_economica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.PosizioneEconomica', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Punteggio per Bonus Anzianità di servizio',
                'verbose_name_plural': 'Punteggi per Bonus Anzianità di servizio',
            },
        ),
    ]
