# Generated by Django 2.2.9 on 2021-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0098_auto_20211021_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='agevolazione_modalità',
            field=models.CharField(choices=[(0, 'Nessuna'), (1, 'Moltiplicazione'), (2, 'Punteggio aggiuntivo')], default=0, max_length=1, verbose_name='Modalità bonus'),
        ),
    ]
