# Generated by Django 2.2.9 on 2021-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0102_auto_20211021_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bando',
            name='agevolazione_soglia_anni',
            field=models.IntegerField(default=3, help_text="Anzianità di servizio nella stessa posizione economica per usufruire del bonus del punteggio relativo all'anzianità di servizio", verbose_name='Anni permanenza minimi per bonus punteggio anzianità'),
        ),
    ]
