# Generated by Django 2.2.9 on 2021-10-22 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0105_auto_20211021_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='punteggio_max',
            field=models.FloatField(default=0, help_text="punteggio massimo attribuibile per ogni anno/mese di servizio. Deve essere un numero positivo moltiplicabile per la  durata dichiarata dall'utente istante", validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
