# Generated by Django 2.2.9 on 2021-10-22 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0106_punteggio_anzianita_servizio_bonus_punteggio_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='punteggio_max',
            field=models.FloatField(help_text='punteggio massimo attribuibile. Deve essere un numero positivo', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
