# Generated by Django 2.2.9 on 2021-10-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0108_auto_20211022_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bando',
            name='agevolazione_soglia_anni',
        ),
        migrations.AddField(
            model_name='moltiplicatore_anzianita_servizio_bonus',
            name='agevolazione_soglia_anni',
            field=models.IntegerField(default=3, help_text='Anzianità di servizio nella stessa posizione economica per usufruire del bonus', verbose_name='Anni permanenza minimi per bonus punteggio anzianità'),
        ),
        migrations.AddField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='agevolazione_soglia_anni',
            field=models.IntegerField(default=3, help_text='Anzianità di servizio nella stessa posizione economica per usufruire del bonus', verbose_name='Anni permanenza minimi per bonus punteggio anzianità'),
        ),
    ]
