# Generated by Django 2.2.9 on 2021-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0112_auto_20211026_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='unita_temporale',
        ),
    ]
