# Generated by Django 2.2.9 on 2021-10-27 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0113_remove_punteggio_anzianita_servizio_bonus_unita_temporale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='punteggio',
            field=models.FloatField(help_text="punteggio attribuito per ogni mese di servizio. Deve essere un numero positivo moltiplicabile per la  durata dichiarata dall'utente istante", validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
