# Generated by Django 2.2.9 on 2021-10-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0115_punteggio_anzianita_servizio_bonus_range_applicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio_anzianita_servizio_bonus',
            name='range_applicazione',
            field=models.IntegerField(choices=[(0, 'Tutto'), (1, 'Solo periodo attuale permanenza'), (2, 'Solo periodo oltre validità minima')], default=2, help_text='Specifica il range di applicazione del bonus', verbose_name='Applicazione bonus'),
        ),
    ]
